version: "3.7"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    image: neuro-jupyter
    #command: sh -c "jupyter lab --port=8890 --ip=0.0.0.0 --allow-root --no-browser --ServerApp.token=''"
    hostname: neuro-jupyter
    container_name: neuro-jupyter
    volumes:
       - .:/main
    environment:
      - JUPYTER_CONFIG_DIR=/main/.jupyter
    ports:
      - "8890:8890"
    restart: always
