version: "3.7"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.spm
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    image: spm-jupyter
    command: sh -c "jupyter lab --port=8899 --ip=0.0.0.0 --allow-root --no-browser --ServerApp.token=''"
    hostname: spm-jupyter
    container_name: spm-jupyter
    volumes:
       - .:/main
    environment:
      - JUPYTER_CONFIG_DIR=/main/.jupyter
    ports:
      - "8899:8899"
    restart: always
